Drop Table MatchStats;
Drop Table Starts;
Drop Table Matchs;
Drop Table HasAPosition;
Drop Table Positions;
Drop Table ParticipatesIn;
Drop Table League;
Drop Table Starters;
Drop Table Cards;
Drop Table Shots;
Drop Table Assists;
Drop Table Goals;
Drop Table Win;
Drop Table Players;
Drop Table MadeBet;
Drop Table SportsTeams;
Drop Table Logo;
Drop Table Bet;
Drop Table Admins;
Drop Table Bettors;
Drop Table Users;

-- Delete from Users;