INSERT INTO Logo (LogoID, Image, Type) VALUES (NULL, LOAD_FILE('/tmp/g2/BarcelonaLogo.png'), 'image/png');
INSERT INTO Logo (LogoID, Image, Type) VALUES (NULL, LOAD_FILE('/tmp/g2/RealMadridLogo.png'), 'image/png');
INSERT INTO Logo (LogoID, Image, Type) VALUES (NULL, LOAD_FILE('/tmp/g2/AtleticoMadridLogo.png'), 'image/png');
INSERT INTO Logo (LogoID, Image, Type) VALUES (NULL, LOAD_FILE('/tmp/g2/SevillaLogo.png'), 'image/png');
INSERT INTO Logo (LogoID, Image, Type) VALUES (NULL, LOAD_FILE('/tmp/g2/RealSociedadLogo.png'), 'image/png');
INSERT INTO Logo (LogoID, Image, Type) VALUES (NULL, LOAD_FILE('/tmp/g2/AthleticBilbaoLogo.png'), 'image/png');
INSERT INTO Logo (LogoID, Image, Type) VALUES (NULL, LOAD_FILE('/tmp/g2/GetafeLogo.png'), 'image/png');
INSERT INTO Logo (LogoID, Image, Type) VALUES (NULL, LOAD_FILE('/tmp/g2/GranadaLogo.png'), 'image/png');
INSERT INTO Logo (LogoID, Image, Type) VALUES (NULL, LOAD_FILE('/tmp/g2/ValenciaLogo.png'), 'image/png');
INSERT INTO Logo (LogoID, Image, Type) VALUES (NULL, LOAD_FILE('/tmp/g2/OsasunaLogo.png'), 'image/png');
INSERT INTO Logo (LogoID, Image, Type) VALUES (NULL, LOAD_FILE('/tmp/g2/VillarrealLogo.png'), 'image/png');
INSERT INTO Logo (LogoID, Image, Type) VALUES (NULL, LOAD_FILE('/tmp/g2/LevanteLogo.png'), 'image/png');
INSERT INTO Logo (LogoID, Image, Type) VALUES (NULL, LOAD_FILE('/tmp/g2/RealValladolidLogo.png'), 'image/png');
INSERT INTO Logo (LogoID, Image, Type) VALUES (NULL, LOAD_FILE('/tmp/g2/AlavesLogo.png'), 'image/png');
INSERT INTO Logo (LogoID, Image, Type) VALUES (NULL, LOAD_FILE('/tmp/g2/EibarLogo.png'), 'image/png');
INSERT INTO Logo (LogoID, Image, Type) VALUES (NULL, LOAD_FILE('/tmp/g2/RealMallorcaLogo.png'), 'image/png');
INSERT INTO Logo (LogoID, Image, Type) VALUES (NULL, LOAD_FILE('/tmp/g2/RealBetisLogo.png'), 'image/png');
INSERT INTO Logo (LogoID, Image, Type) VALUES (NULL, LOAD_FILE('/tmp/g2/CeltaVigoLogo.png'), 'image/png');
INSERT INTO Logo (LogoID, Image, Type) VALUES (NULL, LOAD_FILE('/tmp/g2/EspanyolLogo.png'), 'image/png');
INSERT INTO Logo (LogoID, Image, Type) VALUES (NULL, LOAD_FILE('/tmp/g2/LeganesLogo.png'), 'image/png');

SELECT * FROM Logo;
-- DELETE FROM Logo;